### ISSUE TITLE
Issue !level [value]

### ISSUE THREAD

**Issue by rodaspinto** [OSL-Works/Steam-Card-Bot-PRO#5]
Everything that is calling about finding out the other person's level or calculating the level is giving an error try to give            
      "!level [value]

**Comment by rodaspinto** [comment]
When i do it tells me undefined

**Comment by Refloow** [comment]
Unfortunately you made mistake while configuring the bot.
All you have to do is to set right steam API key inside of the config.js

Follow this guide:
https://github.com/OSL-Works/Steam-Card-Bot-PRO/wiki
